#!/bin/sh

/bin/bash ~/.screenlayout/triple.sh

export SCRIPTPATH
SCRIPTPATH="$( cd "$(dirname "$0")" || exit; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

# Boot picom or compton if it exists
picom --experimental-backends > /dev/null &

leftwm command "LoadTheme $SCRIPTPATH/theme.ron"

feh --bg-scale -z ~/Pictures/wallpapers/
