modkey = "Mod4"
mousekey = "Mod4"
workspaces = [
    { output = "HDMI-1", y = 360, x = 0, height = 1440, width = 2560, id = 2 },
    { output = "DP-2", y = 0, x = 2560, height = 2160, width = 3840, id = 0 },
    { output = "DP-1", y = 360, x = 6400, height = 1440, width = 2560, id = 1},
]
tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
layouts = [
    "MainAndVertStack",
    #"MainAndHorizontalStack",
    "MainAndDeck",
    "GridHorizontal",
    #"EvenHorizontal",
    #"EvenVertical",
    "Fibonacci",
    "LeftMain",
    #"CenterMain",
    "CenterMainBalanced",
    "CenterMainFluid",
    "Monocle",
    #"RightWiderLeftStack",
    #"LeftWiderRightStack"
]
layout_mode = "Workspace"
insert_behavior = "Bottom"
scratchpad = [
]
window_rules = [
]
disable_current_tag_swap = false
disable_tile_drag = true
focus_behaviour = "Sloppy"
focus_new_windows = true

[[keybind]]
command = "Execute"
value = "rofi -show run"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey", "Shift"]
key = "Return"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey"]
key = "s"

[[keybind]]
command = "SoftReload"
value = ""
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "MoveToLastWorkspace"
value = ""
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "SwapTags"
value = ""
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "MoveWindowUp"
value = ""
modifier = ["modkey", "Shift"]
key = "t"

[[keybind]]
command = "MoveWindowDown"
value = ""
modifier = ["modkey", "Shift"]
key = "h"

[[keybind]]
command = "FocusWindowUp"
value = ""
modifier = ["modkey"]
key = "t"

[[keybind]]
command = "FocusWindowDown"
value = ""
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "NextLayout"
value = ""
modifier = ["modkey", "Control"]
key = "t"

[[keybind]]
command = "PreviousLayout"
value = ""
modifier = ["modkey", "Control"]
key = "h"

[[keybind]]
command = "FocusWorkspaceNext"
value = ""
modifier = ["modkey"]
key = "n"

[[keybind]]
command = "FocusWorkspacePrevious"
value = ""
modifier = ["modkey"]
key = "d"

[[keybind]]
command = "MoveWindowUp"
value = ""
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
value = ""
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "FocusWindowUp"
value = ""
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "FocusWindowDown"
value = ""
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "NextLayout"
value = ""
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
value = ""
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "FocusWorkspaceNext"
value = ""
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusWorkspacePrevious"
value = ""
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "o"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "e"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "u"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "comma"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "period"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "p"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "q"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "o"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "e"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "u"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "comma"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "period"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "p"

[[keybind]]
command = "ToggleFullScreen"
modifier = ["modkey"]
key = "space"
